### ISSUE TITLE
Indirect modification of overloaded property App\Http\Requests\FormRequest::$__memoized has no effect

### ISSUE THREAD

**Issue by taylorotwell** [spatie/once#14]
I have a form request that does the following:

```php
    public function source()
    {
        return once(function () {
            return $this->project->user->sources->where(
                'name', $this->source
            )->first();
        });
    }
```

Get the following error: Indirect modification of overloaded property App\Http\Requests\FormRequest::$__memoized has no effect

**Comment by taylorotwell** [comment]
Nevermind, this is a by-product of using once() in a class that has a __get. $foo->__memoized will fall into the get. Solution is to define the __memoized explicitly on the class via property or trait.

**Comment by spaceemotion** [comment]
To add to the solution, make sure that the property is defined as `public`, using `protected` does not seem to work.
