### ISSUE TITLE
Undefined index: type in Backtrace.php

### ISSUE THREAD

**Issue by tylernathanreed** [spatie/once#37]
This happens when the backtrace can't find a "type" index on the backtrace. I'm able to replicate this 100% of the time using `php artisan tinker`.

Example:

```
> php artisan tinker
Psy Shell v0.9.9 (PHP 7.1.11 — cli) by Justin Hileman
>>> once(function() { return rand(1, 1000); })
PHP Notice:  Undefined index: type in S:/Docroot/UAS/portal/vendor/spatie/once/src/Backtrace.php on line 44
```

I'm not certain if there's use-cases beyond tinker that could cause this, but I figured this is worth pointing out.

**Comment by freekmurze** [comment]
Feel free to submit a PR with tests for this that fixes it.
