### ISSUE TITLE
Get different results inside the same request

### ISSUE THREAD

**Issue by jltxwesley** [spatie/once#45]
Have been trying to use this package in a non-laravel project, but `(new MyClass())->getNumber()` always returns different numbers in the same request.

After digging into the source code, I found the `hasBeenSerialized` property in [Listener](https://github.com/spatie/once/blob/master/src/Listener.php) class is always false, when the `__destruct` function being called, it unset the object hash. 

Any ideas why is this happening?

**Comment by freekmurze** [comment]
No idea why this is happend. Can you run the tests?

**Comment by jltxwesley** [comment]
I made a mistake 😒 ,  I initialise a new object each time when calling getNumber function:
```php
// this doesn't work
(new MyClass())->getNumber();
(new MyClass())->getNumber();
```
should invoke the function on the same object:
```php
// this works
$myClass = new MyClass();
$myClass->getNumber();
$myClass->getNumber();
```

Perhaps need to update the README?
`No matter how many times you run (new MyClass())->getNumber() inside the same request you'll always get the same number.`
