### ISSUE TITLE
Using once() on Eloquent models: Object of class Spatie\Once\Listener could not be converted to string

### ISSUE THREAD

**Issue by davidwesdijk** [spatie/once#49]
Dear Spatie,

First of all, thank you for your huge contribution to the open source community. Recently I started using the spatie/once package in our application, mostly for the use of preventing complex queries or external webservice calls within runtime. The results are promising, except for the one issue I encountered; Eloquent models.

For example in the `User`-model, I implemented the following (pseudo-)method:
```php
class User extends Authenticatable
{
    // implementation of the Eloquent model

    public function getCustomerData()
    {
        return once(function() {
            return IntensiveWebserviceCall::getCustomerData($this->id);
        });
    }
}
```

For the most cases the implementation above works perfectly, except when saving the Eloquent model **after** calling the `once()` method. For example:

```php
class SomeController extends Controller
{
    public function updateSomething(User $user)
    {
        $customerData = $user->getCustomerData(); // Calls the once() method

        // Perform some mutations on the User-model
        $user->save();
    }
}
```

The actual `save()` on Eloquent models will fail, throwing the following exception:
`ErrorException: Object of class Spatie\Once\Listener could not be converted to string`

This is because of the attributes been set on the Eloquent model by the method. The `once()` method results in a attribute on the model, and the `save()` methods tries to set this column in the database. Below a part of the dump() before the saving action.  
```
 #attributes: [
    // Rest of the model
    "___once_listener__862505" => Spatie\Once\Listener {
        -hasBeenSerialized: false
        +"objectHash": "000000006190e5420000000021c9fb60"
    }
]
```

I hope this information and examples gives a proper context about the root of this issue. I'm available to provide further information when required. 

Thanks in advance,

David Wesdijk

**Comment by davejamesmiller** [comment]
FYI there's a workaround here:
https://github.com/spatie/once/issues/26#issuecomment-569519243

**Comment by davidwesdijk** [comment]
@davejamesmiller Thank you for your comment and the mention of the workaround. Imo shouldn't this workaround be considered as a solution. 

@freekmurze do you have any thoughts on a sustainable solution?

**Comment by freekmurze** [comment]
I currently don't have the time to dive into this. If there is a bug feel free to submit a PR with tests for me to review.

**Comment by riesjart** [comment]
This no longer appears to be an issue in v3, which doesn't use the `___once_listener__`.
