### ISSUE TITLE
use call_user_func_array instead of call_user_func

### ISSUE THREAD

**Issue by Gummibeer** [spatie/once#58]
Using `call_user_func_array($callback, $backtrace->getArguments())` in the `once()` helper function would allow to use the same arguments in the callback instead of a single `array $args` argument which the user has to decompose himself.

```php
$testClass = new class() {
    public function getNumberForLetter($letter)
    {
        return once(function ($l) {
            return $l . rand(1, 10000000);
        });
    }
};
```

It would also allow for `once()` usage with reference callables for example
```php
public function email($email)
{
    return once('mb_strtolower');
}
```

**Comment by freekmurze** [comment]
If this can be modified in a non-breaking way, I'd accept a PR for this 👍

**Comment by Gummibeer** [comment]
The question is if anyone uses the current behavior. 🤔
It's not documented/described anywhere. The only example with a parent method argument has it in the callback `use` block.
So it's more of a decision to "fix" this and make it official behavior.
Otherwise it would be a next major version to-do.
