### ISSUE TITLE
add callback use arguments to hash

### ISSUE THREAD

**Issue by Gummibeer** [spatie/once#59]
Hey,

right now there's a testcase named for something that doesn't work and tests it by testing a different behavior.
https://github.com/spatie/once/blob/fcd963288f0505a333311a6af1fc14c939f3f058/tests/OnceTest.php#L45-L64

The `it_will_run_the_given_callback_only_once_per_variation_arguments_in_use` test case seems to test a case like
```php
public function domain($email)
{
    $domain = str_after('@', $email);

    return once(function() use ($domain) {
        return mb_strtolower($domain);
    });
}
```

But right now it only uses the arguments of the surrounding method. So this callback is executed once per `$email` and not per `$domain`.
I think we can drop the arguments of the surrounding method by using the arguments of the closure and the "static variables" which can be accessed by `ReflectionFunctionAbstract::getStaticVariables()`.
The combination of both arrays is the list of all accessible variables except the `$this` scope of the object which is partially covered by the object hash which doesn't cover changes to `$this` on runtime - but that's another topic.
I think relying too much on the backtrace method instead of the closure itself isn't useful as it possibly contains variables not used by the `once()` and misses variables used by `once()` but not an argument of the surrounding method.

**Comment by freekmurze** [comment]
Hi Tom,

I currently am short on time to fix this, but I'd accept a PR that improves this!

**Comment by freekmurze** [comment]
I'll review #60 soon. Thanks!
