### ISSUE TITLE
Undefined method Spatie\Once\Cache::getInstance()

### ISSUE THREAD

**Issue by davidjr82** [spatie/once#61]
In documentation, it says that for disabling cache, getInstance method should be used as follows: `Spatie\Once\Cache::getInstance()->disable();` but I get the next error:

```bash
Call to undefined method Spatie\Once\Cache::getInstance()
```

Calling enable and disable works directly:
```php
Spatie\Once\Cache::disable();
Spatie\Once\Cache::enable();
```

Should we change the readme? Or am I missing something? (Also this may applies to flush method)

Thanks!

**Comment by freekmurze** [comment]
The function is defined here: https://github.com/spatie/once/blob/fcd963288f0505a333311a6af1fc14c939f3f058/src/Cache.php#L15
